name: weatherapp_stacked
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  json_annotation: ^4.8.1
  dio: ^5.3.4
  flutter_dotenv: ^5.1.0
  flex_color_scheme: ^7.3.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/Cloud.png
    - assets/images/Cloudy-day.png
    - assets/images/Cloudy-night.png
    - assets/images/droplet.png
    - assets/images/menu-icon.png
    - assets/images/Thunder.png
    - assets/images/wind.png
